### ISSUE TITLE
Hono framework would enhance

### ISSUE THREAD

**Issue by icotd** [conorluddy/Residents#80]
I tried Residents with Hono framework and it's much faster and built-in middleware would make it to easily and quickly implement your ideas. Check https://hono.dev/ . Also since it's a template I would suggest you to make the mail module generic instead of sendgrid, you can use mailpit for local dev. Thanks for starting this great idea!

**Comment by conorluddy** [comment]
Thanks for your feedback! Good call on the mail module, I'll take a look :)
